# Generated by Django 5.2.5 on 2025-09-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('website', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=80)),
                ('salary', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main_app.company')),
            ],
            options={
                'db_table': 'job_positions',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('status', models.CharField(choices=[('Applied', 'applied'), ('Interviewed', 'interviewed'), ('Offer', 'offer'), ('Rejected', 'rejected')], max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.jobposition')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
