# Generated by Django 5.2.5 on 2025-09-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_application_date_applied'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='applications',
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='jobposition',
            table='job_positions',
        ),
    ]
