# Generated by Django 5.2.5 on 2025-09-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_application_table_alter_company_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='main_app.jobposition'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='main_app.company'),
        ),
    ]
