# Generated by Django 5.2.5 on 2025-09-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_application_job_position_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Companies',
        ),
    ]
