# Generated by Django 5.2.5 on 2025-09-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_company_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='title',
        ),
    ]
