# Generated by Django 5.2.5 on 2025-09-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_jobposition_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_position',
            field=models.CharField(max_length=80),
        ),
    ]
