# Generated by Django 5.2.5 on 2025-09-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_application_job_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='company',
        ),
    ]
