# Generated by Django 5.2.5 on 2025-09-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main_app.company'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
