# Generated by Django 5.2.5 on 2025-09-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_jobposition_company_jobposition_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.jobposition'),
        ),
    ]
