# Generated by Django 5.2.5 on 2025-09-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_application_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.jobposition'),
        ),
    ]
