# Generated by Django 5.2.5 on 2025-09-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_application_job_position'),
    ]

    operations = [
    ]
